-- liquibase formatted sql

-- changeset Xsakon:1717516075032-1
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- preconditions-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'articles';
CREATE TABLE "articles" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "title" VARCHAR(255) NOT NULL, "authored" TIMESTAMP WITHOUT TIME ZONE, "published" TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT "articles_pkey" PRIMARY KEY ("id"));

-- changeset Xsakon:1717516075032-2
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- preconditions-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'comments';
CREATE TABLE "comments" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "comment" VARCHAR(255) NOT NULL, "article_id" BIGINT, CONSTRAINT "comments_pkey" PRIMARY KEY ("id"));
ALTER TABLE "comments" ADD CONSTRAINT "article_fk" FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Xsakon:insert-simple-data
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- preconditions-sql-check expectedResult:0 select count(*) from articles
insert into articles (title, authored, published) values( 'Waiter! There is a bug in my JSoup' , now(), null);
insert into articles (title, authored, published) values( 'Beat the Queue with Apache Kafka' , now(), null);
insert into articles (title, authored, published) values( 'How I Stopped Worrying and Learned to Devops My SQL' , now(), null);
insert into comments (comment, article_id) values ('first' , (select max(id) from articles));
insert into comments (comment, article_id) values ('first' , (select min(id) from articles));
insert into comments (comment, article_id) values ('I came here to say that.' , (select min(id) from articles));