-- liquibase formatted sql

-- changeset Xsakon:1717516818000-1
CREATE TABLE "articles" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "title" VARCHAR(255) NOT NULL, "authored" TIMESTAMP WITHOUT TIME ZONE, "published" TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT "articles_pkey" PRIMARY KEY ("id"));

-- changeset Xsakon:1717516818000-2
CREATE TABLE "comments" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "comment" VARCHAR(255) NOT NULL, "article_id" BIGINT, CONSTRAINT "comments_pkey" PRIMARY KEY ("id"));

-- changeset Xsakon:1717516818000-3
ALTER TABLE "comments" ADD CONSTRAINT "article_fk" FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

